notifications:
  email: false
  slack: false

language: go

go:
  - "1.13.x"

addons:
  apt:
    packages:
      - docker-ce

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6

script:
  - make install
  - make linter
  - make build-run

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master